### ISSUE TITLE
Instructions on publishing config and migrations

### ISSUE THREAD

**Issue by odeke** [mtvbrianking/laravel-mtn-momo#12]
Hello,
Please provide more info in the readme on the installation steps. 

Thanks for the package.

**Comment by mtvbrianking** [comment]
@odeke I'll be publishing a stable release later this week. `Watch` the repository for notifications.

**Comment by mtvbrianking** [comment]
@odeke the first 'stable' release; [v0.1.0](https://github.com/mtvbrianking/laravel-mtn-momo/releases/tag/v0.1.0) has been published.
