### ISSUE TITLE
Error Inserting callback URL in Laravel 6.1

### ISSUE THREAD

**Issue by kamyasimon** [mtvbrianking/laravel-mtn-momo#24]
Registering Client ID
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . .
   GuzzleHttp\Exception\RequestException  : cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

  at C:\wamp64\www\myli\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186
    182| 
    183|         // Create a connection exception if it was a specific error code.
    184|         $error = isset($connectionErrors[$easy->errno])
    185|             ? new ConnectException($message, $easy->request, null, $ctx)
  > 186|             : new RequestException($message, $easy->request, $easy->response, null, $ctx);
    187| 
    188|         return \GuzzleHttp\Promise\rejection_for($error);
    189|     }
    190| 

  Exception trace:

  1   GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle))
      C:\wamp64\www\myli\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:149

  2   GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
      C:\wamp64\www\myli\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:102

  Please use the argument -v to see more details.

**Comment by mtvbrianking** [comment]
Hello,

This an MTN MOMO API SSL certificate issue.

If it's solved on their side, everything will resume to normal.
