### ISSUE TITLE
Failure to get new access token

### ISSUE THREAD

**Issue by KebronFishaye** [mtvbrianking/laravel-mtn-momo#26]
Hello
Every time i try to test in my terminal your Usage code i get this error 

> Bmatovu\OAuthNegotiator\Exceptions\TokenRequestException with message 'Unable to obtain a new access token.'

please tell me what to do

**Comment by mtvbrianking** [comment]
@KebronFishaye the failure to request a new access token can result from wrong credentials,

Steps to debug;

1. Confirm the configurations are set

- Client ID & Secret are present in your `.env` file, like this...

```
MOMO_CLIENT_ID="b30db6c2-f8e6-4b18-970f-08a2cc7c4786"

MOMO_CLIENT_SECRET="d789ef81805d4e50b1cfc79f2a53242b"
```

2. Confirm you client is registered with MTN MOMO API

- See: https://github.com/mtvbrianking/laravel-mtn-momo#getting-started

**Comment by KebronFishaye** [comment]
Well I have subscribed to collection product and even submitted an application

And I have client id and secret in my .env file

What else can I do to debug?

Sent from Mail for Windows 10

**Comment by KebronFishaye** [comment]
Can you please send me your whatsup number, so that we can communicate more easily?


Sent from Mail for Windows 10

**Comment by mtvbrianking** [comment]
Share you're email, I'll share my phone number via mail.

Mine is: mtvbrianking@gmail.com
