### ISSUE TITLE
During the registration of client id, i get this error

### ISSUE THREAD

**Issue by 16isaac89** [mtvbrianking/laravel-mtn-momo#28]
GuzzleHttp\Exception\RequestException  : cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

  at \vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:201
    197| 
    198|         // Create a connection exception if it was a specific error code.
    199|         $error = isset($connectionErrors[$easy->errno])
    200|             ? new ConnectException($message, $easy->request, null, $ctx)
  > 201|             : new RequestException($message, $easy->request, $easy->response, null, $ctx);
    202| 
    203|         return \GuzzleHttp\Promise\rejection_for($error);
    204|     }
    205| 

  Exception trace:

  1   GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle))
      vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:155

  2   GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
   vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:105

**Comment by mtvbrianking** [comment]
This occurs the SSL certification for the MTN MOMO API can't be resolved.

I've added an option for users to disable SSL certification while using the package. 
This feature is now available in release [v2.0.1](https://github.com/mtvbrianking/laravel-mtn-momo/releases/tag/v2.0.1)

[Disable ssl certification verification](https://github.com/mtvbrianking/laravel-mtn-momo/blob/master/config/mtn-momo.php#L177)

**Comment by 16isaac89** [comment]
I get a 400 bad request response after making the changes
