### ISSUE TITLE
Add support for using multiple products in the same application.

### ISSUE THREAD

**Issue by mwakaambrose** [mtvbrianking/laravel-mtn-momo#30]
Hye, great work here by the way.

I would like to use both disbursements and collections but during the setup, you can only choose one product. Is there a way to do this? is it currently possible?

I get 
`Bmatovu \ OAuthNegotiator \ Exceptions \ TokenRequestException
Unable to obtain a new access token.` when I try to use a second product after the first one have been registered.

Thanks

**Comment by mwakaambrose** [comment]
Nevermind, I actually got it to work by running the init again and choosing those other products I wanted and completing the setup.

**Comment by mtvbrianking** [comment]
@mwakaambrose the app providers the possibility to use any of the 3 products/services (collection, disbursement, and remittance), one a time.

To use more than one product in the same project, simultaneously; you will have to create a separate  **[oauth token broker](https://github.com/mtvbrianking/oauth-negotiator)** for each product.

**Comment by stevebaros** [comment]
> @mwakaambrose the app providers the possibility to use any of the 3 products/services (collection, disbursement, and remittance), one a time.
> 
> To use more than one product in the same project, simultaneously; you will have to create a separate **[oauth token broker](https://github.com/mtvbrianking/oauth-negotiator)** for each product.

There is no clear documentation for creating a separate oauth token broker [here](https://github.com/mtvbrianking/oauth-negotiator) anyway i can go about that .

**Comment by mtvbrianking** [comment]
I'll try implementing this and releasing it with Laravel v7.x

**Comment by mtvbrianking** [comment]
https://github.com/mtvbrianking/laravel-mtn-momo/releases/tag/v3.0.0

**Comment by stevebaros** [comment]
Ohhhhh , so i have to migrate my app to Laravel & before i can consume the
fix.

*Barungi Stephen*
Developer/ Programmer /ICT consultant
Co-founder & CTO Ham Apps and software LTD
Call: +256775054357 / +256702888123
Alt-Email: sbarungi@hamsoftug.com
Visit: My Blog <https://stevebaros.me/> | My GitHub
<https://github.com/stevebaros> | My Twitter
<https://twitter.com/stevebaros> | My Medium
<https://medium.com/@stevebaros>
Building good and simple software for common use !.

**Comment by mtvbrianking** [comment]
The updates have breaking changes, therefore, we couldn't release these for 2.x

However, we shall try to come up with a migration guide from 2.x to 3.x

**Comment by yvesniyo** [comment]
For me to work I just did this  `php artisan mtn-momo:request-secret`
