### ISSUE TITLE
array_emerge: Argument #2 is not an array: error while installing laravel-mtn-momo

### ISSUE THREAD

**Issue by DallingtonAsin** [mtvbrianking/laravel-mtn-momo#34]
![CaptureMomo](https://user-images.githubusercontent.com/30871119/72204034-b37f1900-3484-11ea-83c3-e6dd7637b1aa.PNG)

Above is an image showing an error i encountered while installing laravel mtn momo for laravel 6, I will be so glad if anyone helps with the solution, thank you!

**Comment by mtvbrianking** [comment]
@DallingtonAsin which version of Laravel are you using?

**Comment by DallingtonAsin** [comment]
It is version 6.10.1 as you can see in the attached png file...though it
finally worked but after several attempts of failing
And i never changed anything to make it work...i only tried running the
command "  composer require bmatovu/laravel-mtn-momo " on console until it
finally worked...Thanks for the package though....although i havent tried
to integrate it into my laravel app as required but am hopeful that it will
help me alot.

Thanks
Dallington Asingwire
Software Engineering MUK

**Comment by DallingtonAsin** [comment]
Thanks
