### ISSUE TITLE
Remittance dont work in tinker

### ISSUE THREAD

**Issue by yndinga** [mtvbrianking/laravel-mtn-momo#36]
I want to use the transfer of funds from mtn with your package, instead collection when I put remittance it does not work in tinker.

 I work with laravel, here is a part of my controller:

namespace App\Http\Controllers;
use Bmatovu\MtnMomo\Products\Remittance;
use Bmatovu\MtnMomo\Exceptions\RemittanceRequestException;
use Illuminate\Http\Request;

class MomoController extends Controller
{
    try {
        $remittance = new Remittance();

        // Request a user to pay
        $momoTransactionId = $remitance->transact('transactionId', '07XXXXXXXX', 100);
    } catch(RemittanceRequestException $e) {
        do {
            printf("\n\r%s:%d %s (%d) [%s]\n\r",
                $e->getFile(), $e->getLine(), $e->getMessage(), $e->getCode(), get_class($e));
        } while($e = $e->getPrevious());
    }

thank you in advance

**Comment by mtvbrianking** [comment]
Your issue indicates no problem whatsoever, what error are you getting?

**Comment by mtvbrianking** [comment]
Refer to issue #37
