### ISSUE TITLE
Unable to obtain a new access token

### ISSUE THREAD

**Issue by frankboris** [mtvbrianking/laravel-mtn-momo#48]
I getting this error when try to get balance or request to pay on live environment

Bmatovu\OAuthNegotiator\Exceptions\TokenRequestException {#1492 ▼
  #message: "Unable to obtain a new access token."
  #code: 0
  #file: "/home/orionass/orionpay/vendor/bmatovu/oauth-negotiator/src/OAuth2Middleware.php"
  #line: 275
  trace: {▶}
}

**Comment by mtvbrianking** [comment]
Am hoping you tested everything in Sandbox first.

You will need to update your configurations when switching to live

Ref: 
https://github.com/mtvbrianking/laravel-mtn-momo/wiki/Go-Live

**Comment by mtvbrianking** [comment]
Confirm the credentials your live credentials via 

`php artisan tinker`

`config('mtn-momo');`
