### ISSUE TITLE
400 Bad Request response 

### ISSUE THREAD

**Issue by kamasuPaul** [mtvbrianking/laravel-mtn-momo#50]
Whenever i use the `$collection->requestToPay($transactionId, $partyId, $amount)
` i get an exception. when i print the exception it states a 400 bad request . Here is the exception
`\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Client error: `POST https://ericssonbasicapi1.azure-api.net/collection/v1_0/requesttopay` resulted in a `400 Bad Request` response (400) [GuzzleHttp\Exception\ClientException]`

Am wondering what could be the possible causes of that. despite being able  to verify the a telephone number is active using this
`$collection->isActive($partyId)` without any excepitons

**Comment by mtvbrianking** [comment]
Are you in sanbbox or live environment?

**Comment by kamasuPaul** [comment]
Hey, thanks for the reply.
Am testing  live environment using my computer on localhost

**Comment by mtvbrianking** [comment]
On live environment it won't work

Remember MTN enforces an IP whitelist, only requests from that IP will be allowed "requestToPay"

**Comment by kamasuPaul** [comment]
Ooh, i didn't know that. Thanks alot @mtvbrianking
