### ISSUE TITLE
Creating a request to pay fail 

### ISSUE THREAD

**Issue by yvanmonk** [mtvbrianking/laravel-mtn-momo#51]
When i type in tinker **$momoTransactionId = $collection->requestToPay('transactionId', '46733123453', 100);**  here's the answer it returns to me **Bmatovu/OAuthNegotiator/Exceptions/TokenRequestException with message 'Unable to obtain a new access token.'**
any solutions ?? thanks
![transactionFail](https://user-images.githubusercontent.com/40157551/90692025-49292500-e26c-11ea-97e7-dd0ff0c77e76.jpg)

**Comment by mtvbrianking** [comment]
Confirm the credentials via tinker

**Comment by yvanmonk** [comment]
It's okay. I managed to solve the problem myself. 
in fact after having made the last command notably php artisan mtn-momo:request-secret I omitted to make a php artisan config:cache 
![error_resolve](https://user-images.githubusercontent.com/40157551/90728803-7225d600-e2bd-11ea-88e5-89812a3ef2ea.jpg)
