### ISSUE TITLE
Call to undefined method requestTopay()

### ISSUE THREAD

**Issue by 16isaac89** [mtvbrianking/laravel-mtn-momo#53]
i get this error Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Bmatovu\MtnMomo\Products\Collection::requestToPay() in file.
am using laravel 6, i checked the collection class and that method is missing

**Comment by mtvbrianking** [comment]
Laravel 6 is pointing to package [branch v2.x](https://github.com/mtvbrianking/laravel-mtn-momo/tree/2.0)

Use 

```diff
- $collection->requestToPay(...);
+ $collection->transact(...);
```

Ref: [Documentation](https://mtvbrianking.github.io/laravel-mtn-momo/2.0/Bmatovu/MtnMomo/Products/Collection.html#method_transact)

**Comment by 16isaac89** [comment]
clear thank you
