### ISSUE TITLE
Not a issue but question

### ISSUE THREAD

**Issue by 16isaac89** [mtvbrianking/laravel-mtn-momo#54]
How do i get the whole response object not only the transactionid but the message also thanks

**Comment by mtvbrianking** [comment]
Actually the response from MTN MOMO API is [200 Accepted](https://httpstatuses.com/202) with no content.

So, you can use to use the [getTransactionStatus($momoTransactionId)](https://mtvbrianking.github.io/laravel-mtn-momo/2.0/Bmatovu/MtnMomo/Products/Collection.html#method_getTransactionStatus) method to get the transaction details.

[Read more](https://momodeveloper.mtn.com/docs/services/collection/operations/requesttopay-POST)
