### ISSUE TITLE
Package Installing Error.

### ISSUE THREAD

**Issue by developerdesigner18** [mtvbrianking/laravel-mtn-momo#56]
Hello,

- I am implementing the mtn payment system with the laravel.  But I am getting troubles with installing the package using this command.

- Please have a look at this screenshot. https://prnt.sc/w5ct5b

- So can you please help me with this.

Thanks

**Comment by mtvbrianking** [comment]
The error looks like a composer path issue.

To confirm so, run `composer update`

**Comment by developerdesigner18** [comment]
But if I will run that then there are also other packages already installed and also maybe they have a dependency for the composer with a lower version. So after doing that maybe some of them will not be work properly.

**Comment by mtvbrianking** [comment]
Actually composer update will only update to the most stable versions.

No need to worry about it breaking anything.

**Comment by developerdesigner18** [comment]
But I am thinking the issue is with the server as I have shared hosting so I do not have the root access for the ssh. So I can not do some things by myself. And even support exe. can not do anything from their end too.

So are you sure about after updating the composer I will not get any issues with the older packages?

**Comment by mtvbrianking** [comment]
I'm afraid, i can't help you diagnosing server issues.

I'll be close this issue, since it's not particularly related to this package.
