### ISSUE TITLE
Add PHP v8 support

### ISSUE THREAD

**Issue by mtvbrianking** [mtvbrianking/laravel-mtn-momo#57]
Most packages are adopting support for PHP 8

Consider adding it too

**Comment by mtvbrianking** [comment]
This should be implemented after switching CI to Github actions

**Comment by mtvbrianking** [comment]
Implemented . 0f4dd9f

**Comment by stevebaros** [comment]
Backward compatibility ?

**Comment by mtvbrianking** [comment]
Only for `Laravel versions >= 6`
