### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Scissorsgratemaker** [mtvbrianking/laravel-mtn-momo#61]
how to make check balance on mtn momo with your system and how to test by send nothing on api mtn momo payment

**Comment by stevebaros** [comment]
Mtn Momo API only allows you to check balance for your collections account not user's balance , to test without spending money , you should use the sandbox environment

**Comment by Scissorsgratemaker** [comment]
ok

**Comment by mtvbrianking** [comment]
@Scissorsgratemaker performing a `requestToPay` action,  you should:

~Check the user's account balance~
[Determine if the user is registered and active](https://mtvbrianking.github.io/laravel-mtn-momo/master/Bmatovu/MtnMomo/Products/Collection.html#method_isActive) i.e they are able to transact using MTN MOMO
