### ISSUE TITLE
Can't install it on Laravel ^9.2

### ISSUE THREAD

**Issue by puzzle29** [mtvbrianking/laravel-mtn-momo#70]
Step to reproduce

- laravel new test
- cd test
- composer require bmatovu/laravel-mtn-momo

And got : 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bmatovu/laravel-mtn-momo[v4.1.0, ..., 4.x-dev] require illuminate/console ^8.0 -> found illuminate/console[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires bmatovu/laravel-mtn-momo ^4.1 -> satisfiable by bmatovu/laravel-mtn-momo[v4.1.0, 4.x-dev].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

---------------------------------------
Screenshot :
https://pic.li/i/Zf3H

**Comment by mtvbrianking** [comment]
Sorry, the package has no release candidate for Laravel 9 yet.

I'll work this over the weekend

**Comment by puzzle29** [comment]
Okay, I see

**Comment by mtvbrianking** [comment]
@puzzle29 [Release v4.20 supports Laravel ^9.0](https://github.com/mtvbrianking/laravel-mtn-momo/releases/tag/v4.2.0)

**Comment by puzzle29** [comment]
ah perfect ,
Thank you.
