### ISSUE TITLE
Fix callback in sandbox

### ISSUE THREAD

**Issue by mtvbrianking** [mtvbrianking/laravel-mtn-momo#74]
**YES. It works in sandbox**

- Change URI to HOST in registerClientId

Default to the application's URL host

`parse_url(config('app.url'))['host']`

- Allow sending a callback URI in requestToPay, if not empty

Validate the domain in the callback URI --- it must match the one registered against the Client App

… create a config entry for the client app host / domain so that you don't query MTN for the same

_It's likely to be a BC_

**Comment by shahadatjuton** [comment]
In which file  "parse_url(config('app.url'))['host']" this code is available?

**Comment by mtvbrianking** [comment]
@shahadatjuton I'll be releasing the fix later today.

Just wait for it, instead of editing files in the vendor dir
