### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by oseip** [mtvbrianking/laravel-mtn-momo#77]
Status: 401 Access Denied

Body: { "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }
please am getting access denied due to invalid subscription key... even though the key provided is correct

**Comment by mtvbrianking** [comment]
Check the logs for the `Ocp-Apim-Subscription-Key` being sent to MTN.

Refer to issue #63 for troubleshooting.

**Comment by oseip** [comment]
Where do I check the logs for the Key being sent and also I used the localhost as my callback url should i change it too.
I am totally confused here

**Comment by mtvbrianking** [comment]
Check in your application logs for the outgoing request
