### ISSUE TITLE
Getting invalid subscription key

### ISSUE THREAD

**Issue by karolsteve** [mtvbrianking/laravel-mtn-momo#78]
{
    "statusCode": 401,
    "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription."
}

**Comment by mtvbrianking** [comment]
Enable application debugging in `.env`

```properties
APP_DEBUG=true
```

From your app logs, confirm the `Ocp-Apim-Subscription-Key` being sent to MTN.

Compare it to what's being set on [MTN Developer Profile](https://github.com/mtvbrianking/laravel-mtn-momo#prerequisites)
